SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS library
DEFAULT CHARACTER SET utf8;
USE library ;


CREATE TABLE IF NOT EXISTS books (
title varchar(50) NOT NULL,
author VARCHAR(50) NOT NULL,
id BIGINT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id))
ENGINE = InnoDB;

ALTER TABLE books
ADD page_count int;
ALTER TABLE books
ADD description VARCHAR (1000);

CREATE TABLE IF NOT EXISTS readers(
id BIGINT NOT NULL AUTO_INCREMENT,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
PRIMARY KEY (id))
ENGINE = InnoDB;

 CREATE TABLE IF NOT EXISTS reader_books(
 reader_id BIGINT NOT NULL,
 book_id BIGINT NOT NULL,
book_out_date DATETIME NOT NULL,
book_return_date DATETIME,
id BIGINT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id))
ENGINE = InnoDB;

ALTER TABLE reader_books
ADD FOREIGN KEY (reader_id) REFERENCES readers (id);

ALTER TABLE reader_books
ADD FOREIGN KEY (book_id) REFERENCES books (id);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;